import { test, expect } from '@playwright/test'

test('create problems, protect notes, record attempts, and display API errors', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('A fresh start for your practice')).toBeVisible()
  await page.getByRole('button', { name: 'Add problem', exact: true }).click()
  await page.getByLabel('Problem number').fill('1')
  await page.getByLabel('Name', { exact: true }).fill('Two Sum')
  await page.getByLabel('Topic', { exact: true }).fill('Arrays & Hashing')
  await page.getByLabel('Notes').fill('Use a hashmap to remember complements.')
  await expect(page.getByRole('checkbox', { name: 'Record my first attempt' })).toBeChecked()
  await page.getByRole('checkbox', { name: 'Record my first attempt' }).uncheck()
  await expect(page.getByLabel('Mastery level')).not.toBeVisible()
  await page.getByRole('button', { name: 'Add problem', exact: true }).last().click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByText('Not reviewed', { exact: true })).toBeVisible()
  await expect(page.getByText('Not scheduled', { exact: true })).toBeVisible()
  await expect(page.getByText('Use a hashmap to remember complements.')).not.toBeVisible()
  await page.getByRole('button', { name: 'Show notes' }).click()
  await expect(page.getByText('Use a hashmap to remember complements.')).toBeVisible()
  await page.getByRole('button', { name: 'Hide notes' }).click()
  await expect(page.getByText('Use a hashmap to remember complements.')).not.toBeVisible()

  for (const attempt of [
    { date: '2026-09-20', mastery: 'Solved Independently', next: 'Sep 27, 2026', count: '1' },
    { date: '2026-09-22', mastery: 'Partial Recall', next: 'Sep 24, 2026', count: '2' },
  ]) {
    await page.getByRole('button', { name: 'Record attempt for Two Sum' }).click()
    await page.getByLabel('Completion date').fill(attempt.date)
    await page.getByLabel('Mastery level').selectOption(attempt.mastery)
    await page.getByRole('button', { name: 'Save attempt' }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
    const row = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Two Sum' }) })
    await expect(row.getByRole('cell').nth(3)).toHaveText(attempt.mastery)
    await expect(row.getByRole('cell').nth(4)).toHaveText(attempt.next)
    await expect(row.getByRole('cell').nth(5)).toHaveText(attempt.count)
  }
  await page.getByRole('button', { name: 'Add problem', exact: true }).click()
  await page.getByLabel('Problem number').fill('1')
  await page.getByLabel('Name', { exact: true }).fill('Duplicate')
  await page.getByLabel('Topic', { exact: true }).fill('Arrays')
  await page.getByRole('checkbox', { name: 'Record my first attempt' }).uncheck()
  await page.getByRole('button', { name: 'Add problem', exact: true }).last().click()
  await expect(page.getByRole('alert')).toHaveText('Problem already exists')
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('Duplicate')
  await page.getByLabel('Problem number').fill('206')
  await page.getByLabel('Name', { exact: true }).fill('Reverse Linked List')
  await page.getByLabel('Topic', { exact: true }).fill('Linked List')
  await page.getByRole('button', { name: 'Add problem', exact: true }).last().click()
  await expect(page.getByRole('rowheader', { name: 'Reverse Linked List' })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Partial Recall')).toBeVisible()
  await expect(page.getByText('Not reviewed')).toBeVisible()
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Add problem', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Add problem', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: 'test-results/mobile-form.png', fullPage: true })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()

  await page.route('**/api/problems/summary', route => route.fulfill({ status: 503, body: '' }))
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Request failed (503)')
  await expect(page.getByRole('rowheader', { name: 'Two Sum' })).toBeVisible()
  await page.unroute('**/api/problems/summary')
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.getByRole('alert')).not.toBeVisible()
})


test('add a problem with its first attempt in one request', async ({ page }) => {
  const writes: string[] = []
  page.on('request', request => { if (request.method() === 'POST') writes.push(new URL(request.url()).pathname) })
  await page.goto('/')
  await page.getByRole('button', { name: 'Add problem', exact: true }).click()
  await page.getByLabel('Problem number').fill('70')
  await page.getByLabel('Name', { exact: true }).fill('Climbing Stairs')
  await page.getByLabel('Topic', { exact: true }).fill('Dynamic Programming')
  await expect(page.getByRole('checkbox', { name: 'Record my first attempt' })).toBeChecked()
  await expect(page.getByLabel('Mastery level')).toHaveValue('')
  await page.getByRole('button', { name: 'Add problem', exact: true }).last().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(writes).toEqual([])
  await page.getByLabel('Completion date').fill('2026-09-29')
  await page.getByLabel('Mastery level').selectOption('Learned Solution')
  await page.getByRole('button', { name: 'Add problem', exact: true }).last().click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  expect(writes).toEqual(['/api/problems'])
  const row = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Climbing Stairs' }) })
  await expect(row.getByRole('cell').nth(3)).toHaveText('Learned Solution')
  await expect(row.getByRole('cell').nth(4)).toHaveText('Sep 30, 2026')
  await expect(row.getByRole('cell').nth(5)).toHaveText('1')
  await page.reload()
  await expect(row.getByRole('cell').nth(5)).toHaveText('1')
})
